### ISSUE TITLE
Google as provider for domain with less than 5 characters before '@'

### ISSUE THREAD

**Issue by octave** [afair/email_address#10]
My friend @rymai noticed that if an email with less than 5 characters before the '@' and using a domain that returns google as provider then it returns an error (dns lookup on).

Any ideas why? Thanks!

**Comment by afair** [comment]
Google accounts need to be between 6 and 30 characters. I just re-confirmed on their sign-up page. 

Is this for a gmail address or a domain hosted at google apps. A recent change was made in that case--ensure you are on the latest release, and let me know a valid address that fails.

Thanks!

**Comment by rymai** [comment]
@afair Thanks, this indeed looks like https://github.com/afair/email_address/issues/7 which should now be solved in 0.1.3! /cc @octave

**Comment by octave** [comment]
@rymai @afait Oh great sorry guys! Thank you!
