### ISSUE TITLE
Why email_address say is false for simple valid address foo@example.com?

### ISSUE THREAD

**Issue by tit** [afair/email_address#11]
```bash
$ irb -r email_address
2.3.1 :001 > EmailAddress.valid? 'foo@example.com'
 => false
```

**Comment by afair** [comment]
This is because the gem validates the domain's Mail Exchanger (MX) DNS records. example.com has no MX and is unable to accept email. The syntax of the email is correct, but the email address will not work. You can turn off DNS lookup to get the address to pass validation.

    EmailAddress.error("foo@example.com")
    => "Invalid Host/Domain Name"
    EmailAddress.valid?("foo@example.com", dns_lookup: :off)
    => true

**Comment by tit** [comment]
@afair, you are a wizard!
Thank you very much.
I promise, always, always carefully read the documentation, and only then ask questions!

**Comment by afair** [comment]
@tit It was a good question! The documentation is terse for starter usage. That should get better in the next releases.
