### ISSUE TITLE
Local part containing `-_` converted to `-` with "normal"

### ISSUE THREAD

**Issue by bartoszkopinski** [afair/email_address#12]
>Normal - The edited form of any input email address. Typically, it is lower-cased and minor "fixes" can be performed, depending on the configurations and email address provider.

I guess the issue here is that it doesn't specify what kind of fixes it performs. Looks like it's trying to do too much. I would expect these addresses to be normalised without any breaking changes.

Here are some examples:

```ruby
irb(main):006:0> EmailAddress.new("sample-_@hotmail.co.uk").normal
=> "sample-@hotmail.co.uk"
```

```ruby
irb(main):012:0> EmailAddress.new("sample-_test@hotmail.co.uk").normal
=> "sample-test@hotmail.co.uk"
```

```ruby
irb(main):024:0> EmailAddress.new("sample.-_test@hotmail.co.uk").normal
=> "sample.test@hotmail.co.uk"
```

**Comment by afair** [comment]
I agree some of these "fixes" are odd right now. They should evolve as the project matures.

These can be turned off with a configuration option:

    EmailAddress.new("sample-_@hotmail.co.uk", local_fix: false).normal
    => "sample-_@hotmail.co.uk"

(See the "Configuration" section on the readme. These can be set per app rather than per invocation.)

I'll leave this open to look at the next time I'm hacking in here.

**Comment by bartoszkopinski** [comment]
@afair Thanks, `local_fix` should work. I think this part is causing problems: 
> condense multiple punctuations

https://github.com/afair/email_address/blob/14f1e9745285f26ed779e507109bc2a0e2622836/lib/email_address/local.rb#L128

Looks like it was meant to fix duplicated characters only.

**Comment by afair** [comment]
I'm closing this issue. That line referenced above has been removed and things have progressed lately. I'm leaning towards doing less "magic fixing" by default now. Let me know if you think there are still issues. Thanks!
