### ISSUE TITLE
user@localhost not considered valid

### ISSUE THREAD

**Issue by yoones** [afair/email_address#15]
A dot seems expected in the hostname for it to be considered valid. Am I mistaking or is it a bug?

* ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
* Rails 5.1.4

```ruby
irb(main):003:0> EmailAddress::VERSION
=> "0.1.6"
irb(main):005:0> EmailAddress.valid?("user@localhost", dns_lookup: :off, host_validation: :syntax)
=> false
```

**Comment by afair** [comment]
Thanks!

You are correct, it was still checking for a dot, and they are not always required. I've fixed that.

I see that both dns_lookup and host_validation are valid, though only dns_lookup is checked in the code. That should change to host_validation for consistent naming.
