### ISSUE TITLE
Incorrect check

### ISSUE THREAD

**Issue by joaovitoras** [afair/email_address#17]
I believe this check is incorrect. That should be `!valid_dns?`  right?

https://github.com/afair/email_address/blob/62e30e7fa797c5aa9ccf460ad6a2af478667f14d/lib/email_address/host.rb#L394

This this false with valid host

**Comment by afair** [comment]
This is correct and intended. Some domains may be valid but not configured for email via MX records in DNS.

1) Valid domain with properly configured MX records
2) Valid domain (DNS A Record) without MX records (this case)
3) Invalid domain.

**Comment by joaovitoras** [comment]
tks for the explanation
