### ISSUE TITLE
Complete translations in lib/email_address/config.rb:145

### ISSUE THREAD

**Issue by EstevanBR** [afair/email_address#24]
the @errors method is missing some entries for the other errors like `domain_unknown:` for example.

**Comment by msdundar** [comment]
It would be nice if you read this these strings from a YML file:

```
    @errors = {
      invalid_address:    "Invalid Email Address",
      invalid_mailbox:    "Invalid Recipient/Mailbox",
      invalid_host:       "Invalid Host/Domain Name",
      exceeds_size:       "Address too long",
      not_allowed:        "Address is not allowed",
      incomplete_domain:  "Domain name is incomplete",
    }
```

And better if you read current locale of for Rails apps.

**Comment by afair** [comment]
I have moved these messages, and added missing ones, into a YAML file in release 0.1.10, though they are not yet useful outside the library.

Note this is not a Rails-specific library, but perhaps it can be configured to hook into the I18n module for these translations.
