### ISSUE TITLE
Validate top-level domain (TLD)

### ISSUE THREAD

**Issue by iagopiimenta** [afair/email_address#25]
See below:

```ruby
EmailAddress.valid? "email@domain", dnf_lookup: :off, host_validation: :syntax
# => true
```

**Comment by afair** [comment]
It can't completely check if the TLD is valid without a DNS check, but I'm requiring that at least one dot is there for a probably Fully-Qualified Domain Name (FQDN) when it isn't localhost.

Also, your example has a typo "dnf_lookup" should be "dns_lookup" :-)
