### ISSUE TITLE
Getting "Mailbox name too short" on a 4-digit mailbox name

### ISSUE THREAD

**Issue by joshnabbott** [afair/email_address#31]
I've read through the source code and it looks to me like a 4-digit mailbox name should be considered valid. By default it looks like it's set to `1..64`, however, I still get this error:

```
irb(main):098:0> EmailAddress.error 'josh+subscribers@exposure.co'
=> "Mailbox name too short"
```
I'm using Rails 4.2.8 and `email_address (0.1.10)`.

**Comment by tspacek** [comment]
I am getting this on my emails also, since upgrading from `0.1.9`

I suspect it's due to your (and my) nameservers resolving to Google, which is configured to default to a minimum of 5: https://github.com/afair/email_address/blob/master/lib/email_address/config.rb#L136

**Comment by joshnabbott** [comment]
@tspacek good catch. Our emails are working fine however, even with shorter mailbox names. Just not passing validation with the gem. I'll try bumping back down to  `0.1.9`.

**Comment by afair** [comment]
Thanks for finding this. Release v0.1.11 has this fix.
