### ISSUE TITLE
Uninitialized constant

### ISSUE THREAD

**Issue by lloydwatkin** [afair/email_address#33]
In a user activerecord model (done this way so I can have additional checks):

```ruby
def check_email
      email_address = ::EmailAddress.new(email)
      if false == email_address.valid?(email)
        errors.add(:email, 'invalid email address provided')
      end
end
```

**Error: Uninitialized constant EmailAddress**

If I require 'email_address' at the top of the file my server crashes on start up with no error message (obviously the gem is in my Gemfile). Any idea what could be going on?

```
lloyd@xps13:~/Sites/api$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
lloyd@xps13:~/Sites/api$ rails -v
Rails 4.2.10
```

Also runs file in development. I can start server with `RAILS_ENV` set to production or staging just fine. Only on staging server is this causing an issue.

Server setup:

```
$:~$ ./bin/rails --version
Rails 4.2.10
$:~/$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

**Comment by lloydwatkin** [comment]
If I open rails console on the staging server all is well:

```
$:~$ RAILS_ENV=staging ./bin/rails c
I, [2018-07-25T16:49:07.934395 #6551]  INFO -- sentry: ** [Raven] Raven 2.7.3 ready to catch errors
Loading staging environment (Rails 4.2.10)
irb(main):001:0> require 'email_address'
=> false
irb(main):004:0> e = EmailAddress.new('lloyd@evilprofessor.net')
=> #<EmailAddress::Address:0x2aceeb927ce8 address="lloyd@evilprofessor.net">
irb(main):005:0> e.valid?
=> false
irb(main):007:0> e.error
=> "Domain name not registered"

**Comment by lloydwatkin** [comment]
```
$:~/olio/current$ grep email_address Gemfile.lock
    email_address (0.1.11)
  email_address

**Comment by afair** [comment]
Hi,

I'm not sure this is an issue with the gem. Also, your explanation is confusing and seemingly contradictory. Can you clarify or paste a failure case?

    Also runs file (fine?) in development.
    I can start server with RAILS_ENV set to production or staging just fine.
    Only on staging server is this causing an issue.
    If I open rails console on the staging server all is well

In rails, you shouldn't have to require the gem in your file, it will load automatically. You would only need to require ruby standard libraries not already loaded by rails, for example:

    require 'fileutils'

In your Gemfile, does the "gem 'email_address" occur inside of a "group" block where it won't be loaded for certain environments? Also, does "bundle install" run cleanly?

Is there a startup error or other useful information logged in ./log/staging.log ?

**Comment by lloydwatkin** [comment]
Apologies, a couple of typos haven't helped.

In my gemfile the gem isn't in a block (is available in all environments). Also `bundle install` runs cleanly.

On my development machine: all works ok. 
On staging: `EmailAddress` not defined (hence me trying require, I'm aware it shouldn't be needed). However, if I open the ruby console on the staging server `EmailAddress` is available.

Nothing useful in the log, I just see the server constantly restarting when including require. If I don't have the require then on staging I get not defined error.

Haven't seen this issue with other gems. I thought it was a conflict with `validates_email_format_of` but that's not the case.

**Comment by lloydwatkin** [comment]
I knew something weird was going on! I restarted the server this morning and its fixed everything. Thanks for a great gem :+1:
