### ISSUE TITLE
Emails with trailing underscores are falsely identified as invalid

### ISSUE THREAD

**Issue by JoelESvensson** [afair/email_address#35]
I just ran email_address against a big email list I have, and it works fine except for that several emails with trailing underscores in the local part are identified as invalid emails.
I'm not that familiar with the deep details of email validation, but maybe just allow trailing underscores? Even though it might not be 100% according to some spec

**Comment by afair** [comment]
Hi,

Yes addresses ending with an underscore is RFC-compliant, but "suspicious" as a well-formed user address in what we call "conventional". You can add `local_format: :standard` as an option to the valid?() call which will consider your address as an RFC standard address.

Is this address from a large email provider (google, msn, yahoo, aol ,etc)? Those shouldn't end in the underscore, but private mail hosts can do anything, but still seem suspicious as a "formal" personal address. I may need to reconsider such formulations.

**Comment by legolin** [comment]
I also recently ran into this (a hotmail address).  As of the last time I checked, outlook.com lets me create emails with trailing underscore.

**Comment by lloydwatkin** [comment]
I'm seeing a similar error with a hyphen:

```ruby
2.6.5 :003 > email = 'lloyd+-@olioex.com'
 => "lloyd+-@olioex.com" 
2.6.5 :004 > ::EmailAddress.new(email).valid?
 => false

**Comment by afair** [comment]
Ah, I see. The address tag could be any reasonable set of characters, but the mailbox part (lloyd) would need to conform. Standard format will work, but may be too lax for user email addresses. Upcoming work should address this better, I'll see what I can do for this branch.

**Comment by babaralishah** [comment]
Hi 
I am on Angular

And using the below regex:

`'^[a-z0-9]+([._-]?[a-z0-9]+)+@[a-z0-9]+([._-]?[a-z0-9]+)+\\.[a-z]{2,3}$'`

But its not fulfilling my requirement, my requirement is below:

`saa5@me-d_d_u.co`

please anyone tell me, why this regex is not working for my above mentioned case.

Regards
Babar Ali Shah

**Comment by afair** [comment]
Your problem is the \\. in the match which needs to only be \. to match a period. \\. Will match a \ followed by any character.
Search the web for a "regex tester" to build it interactively.

BTW, this is not a good regex for email because it is too simple to cover most cases. Also, _ is not allowed in domain names.
