### ISSUE TITLE
Typo on README.md

### ISSUE THREAD

**Issue by eclemens** [afair/email_address#36]
In the main README the following line is wrong
```
EmailAddress::Config.setting( local_format: :relaxed )
```
it should be
```
EmailAddress::Config.setting( :local_format, :relaxed )
```

**Comment by AlexWayfer** [comment]
Maybe we should change the code for `local_format: :relaxed`?

**Comment by eclemens** [comment]
No, the comma format is correct. We already have EmailAddress::Config.configure forthe other format.

So, it should be:
```EmailAddress::Config.setting(:local_format, :relaxed)```
or
```EmailAddress::Config.configure(local_format: :relaxed)```

Someone got confused and added the incorrect format on the `README.md` file.

**Comment by afair** [comment]
Thanks for pointing this out. @eclemens you are correct. I revised the README accordingly. 😄
