### ISSUE TITLE
Why is the period not removed for certain domains?

### ISSUE THREAD

**Issue by MaxPleaner** [afair/email_address#4]
Given an email like `email = "MAX.PLEANER@ATT.NET`

I thought when I ran `EmailAddress.canonical email` then it would be "maxpleaner@att.net",

however it's just downcasing and not removing the period. The result is `max.pleaner@att.net`

Is this correct and I don't realize it? I thought the periods in email addresses were not part of the unique identifier. When I change `ATT.NET` to `GMAIL.COM` then the period is removed, though.

**Comment by afair** [comment]
Max,

Yes, this is correct.

As far as I know, these magic, non-significant periods are only used by Gmail and Google Apps email accounts. The configuration for Google email addresses has been set up to remove them upon canonicalization, and not for any other domains. 

Email sent to "max.pleaner", "maxpleaner", or "m.a.x..p.l.e.a.n.e.r" at gmail should go to the same account, but that is only true for Google, not part of the Email Address Standard. Those mailboxes are likely to be separate accounts on other Email Providers.
