### ISSUE TITLE
netaddr dependency needs to be upgraded

### ISSUE THREAD

**Issue by joshnabbott** [afair/email_address#46]
NVD reports a vulnerability in the version of `netaddr` being used. Dependencies need to be update for the patch.

**Comment by onyxraven** [comment]
I noticed this gem uses NetAddr::CIDR https://github.com/afair/email_address/blob/cdecee6ce0b2d338416f4b1bedd09193f0479e12/lib/email_address/host.rb#L319 - NetAddr gem 2.0 removes this class. 

I believe the behavior can be replicated with `IPAddr.new(cidr).include?(ip)`
