### ISSUE TITLE
EmailAddress.normal can be extremely slow for certain mail addresses

### ISSUE THREAD

**Issue by cseelus** [afair/email_address#50]
I played around with our Rails app, which uses `EmailAddress.normal('some_mail_address', host_encoding: :unicode)` to show previously normalized mail addresses in a format which is more readable to our Users, to test something unrelated to this issue.

After creating a fake User with the mail address `asdf@dafsd.de`, I noticed that the view which uses `EmailAddress.normal('asdf@dafsd.de', host_encoding: :unicode)` took a few seconds to render.

After some debugging, I found that I could reproduce this issue (IRB output):

```ruby
require 'benchmark'
=> true
require 'email_address'
=> true
puts Benchmark.measure { EmailAddress.normal("asdf@dafsd.de", host_encoding: :unicode) }
  0.002057   0.001057   0.003114 (  4.149702)
=> nil
```

So calling `EmailAddress.normal` in this case takes more than 4 seconds (!) on my 2018 MacBook Pro with Ruby 2.6.5 and version 0.1.12 of this gem installed.

**Comment by AlexWayfer** [comment]
```
> puts Benchmark.measure { EmailAddress.normal("asdf@dafsd.de", host_encoding: :unicode) }
  0.001084   0.000292   0.001376 (  0.003397)
```

Maybe there are some delays with network? `EmailAddress` can check MX records.

Or you can try to debug with something like `rbspy`.

**Comment by cseelus** [comment]
Thanks for the quick reply. Seems to be big network delays, as the domain does not exist. Setting `EmailAddress::Config.setting(:host_validation, :syntax)` does the trick.

**Comment by AlexWayfer** [comment]
I guess, if you see small number in the first three columns (`user`, `system` and `total`) and a large one in the last (`real`) — this is I/O time (memory or network).

**Comment by cseelus** [comment]
Yes, indeed …
