### ISSUE TITLE
Have Instance level config

### ISSUE THREAD

**Issue by kjg** [afair/email_address#51]
I would love the config to not be global. It would be super useful to sometimes validate only the syntax of the email address, like maybe when importing a list of people, but other times do a more strict check like when a user is changing their own email address, or trying to send an email to a specific address.

**Comment by afair** [comment]
You can override any configuration parameter per instance:

    EmailAddress.valid?("user@domain", host_validation: :syntax)
    EmailAddress.new("user@domain", host_validation: :syntax)
