### ISSUE TITLE
`host_validation: :syntax` making network calls

### ISSUE THREAD

**Issue by garygreyling** [afair/email_address#53]
The docs indicate that running the following will validate the email locally without any network calls:

```ruby
EmailAddress.valid?('my@email.com', host_validation: :syntax)
```

When I run this on a list of 2000 email addresses it runs very slowly, and I get network errors that indicate that its still checking something remotely.

Am I mistaken that `host_validation: :syntax` should make the validation completely offline?

**Comment by VvanGemert** [comment]
Hi Gary,

I've encountered the same issue. You can bypass this by calling:

`EmailAddress.new(email, host_validation: :syntax).valid?`

Or setting a default config:

`EmailAddress::Config.setting(:host_validation, :syntax)`
