### ISSUE TITLE
Fix MSN provider

### ISSUE THREAD

**Issue by 14113** [afair/email_address#56]
I'm using this great gem! Thx for it!

Today, we received a message that one email address: `42762763@outlook.com` is not valid, but it's. Outlook changed rules for email addresses, I think.

We fixed it with like this:
```ruby
EmailAddress::Config.provider(
  :msn,
  domain_match: %w[msn. hotmail. outlook. live.],
  mailbox_validator: ->(m, _t) { m =~ EmailAddress::Local::STANDARD_LOCAL_REGEX }
)
```
It's not the best fix, but it works for us.
Is it a good idea to do PR with changes providers config?

**Comment by AlexWayfer** [comment]
@14113 please, use the search: https://github.com/afair/email_address/issues?utf8=%E2%9C%93&q=MSN

**Comment by 14113** [comment]
Sorry
