### ISSUE TITLE
Custom errors

### ISSUE THREAD

**Issue by jbutler-lifefuels** [afair/email_address#57]
I was trying customize the error messages as per the readme but was unable to get it going. I inspected EmailAddress::Config.error_messages and noticed its a nested hash. So the merge that happens in config.rb appends the keys. I think the merge needs to happen on the inner hash or a deep merge needs to happen. See below:

**Default errors**
```
{
  "en"=>{
    "email_address"=> {
        "address_unknown"=>"Unknown Email Address", 
        "domain_does_not_accept_email"=>"This domain is not configured to accept email", "domain_invalid"=>"Invalid Domain Name", 
        "domain_no_localhost"=>"localhost is not allowed for your domain name", "domain_unknown"=>"Domain name not registered", 
        "exceeds_size"=>"Address too long", 
        "incomplete_domain"=>"Domain name is incomplete", 
        "invalid_address"=>"Invalid Email Address", 
        "invalid_host"=>"Invalid Host/Domain Name", 
        "invalid_mailbox"=>"Invalid Mailbox", 
        "ip_address_forbidden"=>"IP Addresses are not allowed", "ip_address_no_localhost"=>"Localhost IP addresses are not allowed", "ipv4_address_invalid"=>"This is not a valid IPv4 address", 
        "ipv6_address_invalid"=>"This is not a valid IPv6 address", 
        "local_size_long"=>"Mailbox name too long", 
        "local_size_short"=>"Mailbox name too short", 
        "local_invalid"=>"Recipient is not valid", 
        "not_allowed"=>"Address is not allowed", 
        "server_not_available"=>"The remote email server is not available"
    }
  }
}
```

**Overridden errors as a symbol**
```
EmailAddress::Config.error_messages(
    invalid_address: "Please specify a valid email address"
)
```

Output
```
{
  "en"=>{
    "email_address"=> {
        "address_unknown"=>"Unknown Email Address", 
        "domain_does_not_accept_email"=>"This domain is not configured to accept email", "domain_invalid"=>"Invalid Domain Name", 
        "domain_no_localhost"=>"localhost is not allowed for your domain name", "domain_unknown"=>"Domain name not registered", 
        "exceeds_size"=>"Address too long", 
        "incomplete_domain"=>"Domain name is incomplete", 
        "invalid_address"=>"Invalid Email Address", 
        "invalid_host"=>"Invalid Host/Domain Name", 
        "invalid_mailbox"=>"Invalid Mailbox", 
        "ip_address_forbidden"=>"IP Addresses are not allowed", "ip_address_no_localhost"=>"Localhost IP addresses are not allowed", "ipv4_address_invalid"=>"This is not a valid IPv4 address", 
        "ipv6_address_invalid"=>"This is not a valid IPv6 address", 
        "local_size_long"=>"Mailbox name too long", 
        "local_size_short"=>"Mailbox name too short", 
        "local_invalid"=>"Recipient is not valid", 
        "not_allowed"=>"Address is not allowed", 
        "server_not_available"=>"The remote email server is not available"
    }
  },
  :invalid_address=>"Please specify a valid email address"
}
```

**Overridden errors as a string**
```
EmailAddress::Config.error_messages(
    'invalid_address' => "Please specify a valid email address"
)
```

Output
```
{
  "en"=>{
    "email_address"=> {
        "address_unknown"=>"Unknown Email Address", 
        "domain_does_not_accept_email"=>"This domain is not configured to accept email", "domain_invalid"=>"Invalid Domain Name", 
        "domain_no_localhost"=>"localhost is not allowed for your domain name", "domain_unknown"=>"Domain name not registered", 
        "exceeds_size"=>"Address too long", 
        "incomplete_domain"=>"Domain name is incomplete", 
        "invalid_address"=>"Invalid Email Address", 
        "invalid_host"=>"Invalid Host/Domain Name", 
        "invalid_mailbox"=>"Invalid Mailbox", 
        "ip_address_forbidden"=>"IP Addresses are not allowed", "ip_address_no_localhost"=>"Localhost IP addresses are not allowed", "ipv4_address_invalid"=>"This is not a valid IPv4 address", 
        "ipv6_address_invalid"=>"This is not a valid IPv6 address", 
        "local_size_long"=>"Mailbox name too long", 
        "local_size_short"=>"Mailbox name too short", 
        "local_invalid"=>"Recipient is not valid", 
        "not_allowed"=>"Address is not allowed", 
        "server_not_available"=>"The remote email server is not available"
    }
  },
  'invalid_address'=>"Please specify a valid email address"
}
```

**Overridden again**
```
EmailAddress::Config.error_messages(
"en" => {
    'email_address' => {
        'invalid_address' => "Please specify a valid email address"
    }
})
```

Output
```
{
  "en"=>{
    "email_address"=> {
        'invalid_address'=>"Please specify a valid email address"
    }
  }
}
```

**Comment by daveverwer** [comment]
I'm also having problems getting custom error messages to work with `validates_with`. Did you ever get anywhere with this @jbutler-lifefuels?

For me, no matter what I pass to `EmailAddress::Config.error_messages` the field only ever has the same error message, it doesn't matter why the validation fails. If I supply the same bad email address to `EmailAddress.error` I get a much more descriptive error message, but never on the field validation.

I suspect something like this might be at the root of my problem too.

**Comment by jbutler-lifefuels** [comment]
I just ended up overriding all of the values of
EmailAddress::Config.error_messages in an initializer as I didn't have time
to wait for the fix. I would like to go back and see if the updated code
works as expected for me.

**Comment by daveverwer** [comment]
Thanks so much for the extremely quick reply Jim! Would you be open to sharing that initialiser?

**Comment by jbutler-lifefuels** [comment]
Here is what it looks like.

require 'email_address'

# i discovered a bug in the gem so override all the errors here for now
until it can be fixed
EmailAddress::Config.error_messages(
{
"en" => {
"email_address" => {
"address_unknown" => "Unknown Email Address",
"domain_does_not_accept_email" => "This domain is not configured to accept
email",
"domain_invalid" => "Invalid domain name",
"domain_no_localhost" => "localhost is not allowed for your domain name",
"domain_unknown" => "Please provide a valid email address",
"exceeds_size" => "Email address is too long",
"incomplete_domain" => "Domain name is incomplete",
"invalid_address" => "Please provide a valid email address",
"invalid_host" => "Invalid Host/Domain Name",
"invalid_mailbox" => "Invalid Mailbox",
"ip_address_forbidden" => "IP Addresses are not allowed",
"ip_address_no_localhost" => "Localhost IP addresses are not allowed",
"ipv4_address_invalid" => "This is not a valid IPv4 address",
"ipv6_address_invalid" => "This is not a valid IPv6 address",
"local_size_long" => "Mailbox name too long",
"local_size_short" => "Mailbox name too short",
"local_invalid" => "Recipient is not valid",
"not_allowed" => "Address is not allowed",
"server_not_available" => "The remote email server is not available"
}
}
})

**Comment by jbutler-lifefuels** [comment]
One note, as I mentioned before I haven't had time to go back and check the
fix so this is probably not necessary anymore.

**Comment by daveverwer** [comment]
Thank you very much Jim. After checking with your code, you're right this wasn't my issue. 

I can customise the basic error message "Invalid Email Address" with the code in the README, but no matter what's wrong none of the other messages that I put in, or any of the other defaults ever get used. I only ever get "Invalid Email Address".

I'll keep perservering! Thank you so much for your time and help.
