### ISSUE TITLE
Still making DNS requests when `dns_lookup` is `off`

### ISSUE THREAD

**Issue by dark-panda** [afair/email_address#59]
We have the following in our Rails configuration for validating email addresses:

```
EmailAddress::Config.setting(:host_validation, :syntax)
EmailAddress::Config.setting(:dns_lookup, :off) if Rails.env.test?
```

This is to ensure that we aren't making network requests during testing, which slows our tests considerably and would introduce undesirable external effects. As of 0.1.14, this seems to have no effect, and DNS lookups are performed throughout our test suite. Previously, we were using version 0.1.13 and it appeared to be working fine.

**Comment by afair** [comment]
I haven't been able to recreate this exactly. The recent release should have resolved/reduced any DNS operations. But I did find something that could have caused the settings to be clobbered, so formalized how the settings are handled. Could you try this commit on master head and see if it resolves your issue?

Other than that, is there a test case that you can give me that I can work with? It may be a particular domain (or list of them) and any other settings you are using?

**Comment by macgill4444** [comment]
I also ran into this today. I had the code snippet below in an initializer but my test suite was still running super slow. I was on `v0.1.12`. I upgraded to `v0.1.17` and it fixed the issue.

```ruby
EmailAddress::Config.configure(dns_lookup: :off, host_validation: :syntax)
```

**Comment by afair** [comment]
Thanks @macgill4444 I'll close as it seems fixed to us
