### ISSUE TITLE
Dots in a GSuite domain are not the same as in gmail

### ISSUE THREAD

**Issue by dorongutman** [afair/email_address#62]
As you can see in the gmail help doc about dots (https://support.google.com/mail/answer/7436150?vid=0-862679329880-1516155855805&hl=en) the canonical address should disregard dots only if the domain is the gmail domain, and not if it's a g suite domain.
Specifically see the following excerpt from this help doc: 
![image](https://user-images.githubusercontent.com/719298/78569171-e179bc80-782b-11ea-8b09-b58836de916a.png)

To prove this, let's take `boomer.com` as an example. It's a domain that has the MX records of g suite (see https://mxtoolbox.com/SuperTool.aspx?action=mx%3aboomer.com&run=toolpage).
When calling `EmailAddress.canonical('as.df@boomer.com')`, we get `asdf@boomer.com` but that is NOT true.

If you run the same thing on a different domain (non-g suite domain) you'll get the canonical address WITH the dots: `EmailAddress.canonical('as.df@example.com')` outputs `as.df@example.com`

**Comment by dorongutman** [comment]
@afair did you have time to look at this by any chance?

**Comment by afair** [comment]
Thanks for finding the link explaining this!
