### ISSUE TITLE
Address validation `address_local` not implemented

### ISSUE THREAD

**Issue by tessi** [afair/email_address#65]
Hello 👋 

I am about to use this gem for email validation (thanks for all your work here! you really did a lot of good things here, especially saving me from manually doing the punycode conversion).

While going through the [configuration docs in your README](https://github.com/afair/email_address#available-configuration-settings), I noticed that you advertise the following setting:

> address_local: false, Allow localhost, no domain, or local subdomains.

However, after testing it, I found it to not function. After reading through the source code of this gem, I couldn't find any place where you implement this setting.

This is how I use it:

```ruby
EmailAddress.new(
  email_string,
  host_validation: :syntax,
  host_encoding: :punycode,
  local_format: :standard,
  local_encoding: :unicode,
  address_local: false
)
```

Maybe I am using the gem wrong, but to me it looks like this feature is not implemented.

We could either:

1. remove it's description from the README
2. implement the feature

cheers,
tessi

**Comment by afair** [comment]
Thanks for bringing this up! I would lean to removing it, at least until a it is better defined. It also is ambiguous with expanding Fully Qualified Domain Names and allowing them.
