### ISSUE TITLE
Ruby 3.0.0 deprecation: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead

### ISSUE THREAD

**Issue by JasonBarnabe** [afair/email_address#73]
> /home/jason/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/email_address-0.1.20/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.

**Comment by afair** [comment]
Thanks for letting me know. Fixed in 8c02ae5 (next release 0.2.0)
