### ISSUE TITLE
Go to another CI

### ISSUE THREAD

**Issue by AlexWayfer** [afair/email_address#76]
Travis CI is pretty deprecated and buggy, as I know.

There are builds, yes, but where is their status for my PR?

![image](https://user-images.githubusercontent.com/6510020/115396042-3b59e400-a1ed-11eb-8881-85beae622df3.png)

Also you can see https://github.com/tycooon/memery/issues/28 and https://github.com/excpt/moments/issues/3

I'm satisfied with Cirrus CI, but GitHub Actions and Circle CI are good too.

**Comment by afair** [comment]
Merged #77 to move to github actions.
