### ISSUE TITLE
Hotmail email mailbox_validator is incorrect

### ISSUE THREAD

**Issue by jsmilani** [afair/email_address#8]
We found some hotmail emails in our DB that are invalid according to this gem but should be valid. Hotmail seems to support underscores but the mailbox_validator for msn does not.

https://social.technet.microsoft.com/Forums/exchange/en-US/69f393aa-d555-4f8f-bb16-c636a129fc25/what-are-valid-and-invalid-email-address-characters?forum=exchangesvradminlegacy

"e.g., Windows Live Hotmail, for example, only allows creation of email addresses using alphanumerics, dot (.), underscore (_) and hyphen (-)"

**Comment by afair** [comment]
@jsmilani, Thanks for finding this!

That link you gave talks about the email address standard, and while on a Microsoft site, not talk about their MSN/Hotmail/Outlook/Live services. I just tried creating a new account and tried different patterns to see what is valid.

It seems to require a start of a letter, then any letter, digit, _ - and period. Though the full stop (period) does not seem to able to end the name, other punctuation can, and can even occur in succession (e.g. "w.-asdf----") I have changed the regular expression to match this.
