### ISSUE TITLE
Weird addresses are reported as valid

### ISSUE THREAD

**Issue by Chocksy** [afair/email_address#9]
```ruby
2.3.0 :014 > ['example.user@foo.', 'ogog@sss.c', 'example.user@foo.com/'].map { |e| EmailAddress.valid?(e) }
 => [true, true, true]
```

Why is this the case? These emails don't look right.

**Comment by afair** [comment]
@Chocksy,

Thanks for reporting this. I've looked into it and am seeing them reported as invalid on master. I had just fixed other issues before you reported this and that must have resolved this.

I verified gem v0.1.1 does erroneously report these as valid, and gem v0.1.3 now reports these and invalid. `bundle update email_address` and you should be good to go!

Allen

**Comment by Chocksy** [comment]
Sweet @afair
