### ISSUE TITLE
Gmail address validation on old addresses

### ISSUE THREAD

**Issue by mantas** [afair/email_address#91]
Currently Gmail addresses are validate to have 5+ characters long local part. However, old addresses with 4 characters exist. I saw some reports that 3 characters long addresses were available at some point, but never saw one out in the wild.

I'd like to propose to either remove this check from Google/Gmail validation or have a configuration option to skip provider-specific validations.

I can do a PR for whichever solution is preferred.

**Comment by afair** [comment]
I dropped the minimum to 3 characters, as shorter local parts have been reported here. I hope it is long enough to prevent errors and short enough to represent reality. 

Released as v.0.2.4
