### ISSUE TITLE
Canonical does not remove .

### ISSUE THREAD

**Issue by arrowcircle** [afair/email_address#96]
Hey! Just found a small bug:

```ruby
EmailAddress.canonical("test.test@test.com")
=> "test.test@test.com"
```

Should it return `testtest@test.com` instead?

**Comment by afair** [comment]
Hello! The "." is only optional for gmail.com, and it is configured for this as it has become the largest free email provider in recent years. Other providers could have different accounts for "testtest" and "test.test".
